/* tslint:disable */
/* eslint-disable */
/**
 * Task Management Service
 * API for managing tasks for patients, doctors, and administrators.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConsultationTypeRequest
 */
export interface ConsultationTypeRequest {
    /**
     * 
     * @type {string}
     * @memberof ConsultationTypeRequest
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof ConsultationTypeRequest
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof ConsultationTypeRequest
     */
    price?: number;
}

/**
 * Check if a given object implements the ConsultationTypeRequest interface.
 */
export function instanceOfConsultationTypeRequest(value: object): value is ConsultationTypeRequest {
    return true;
}

export function ConsultationTypeRequestFromJSON(json: any): ConsultationTypeRequest {
    return ConsultationTypeRequestFromJSONTyped(json, false);
}

export function ConsultationTypeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConsultationTypeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'description': json['description'] == null ? undefined : json['description'],
        'price': json['price'] == null ? undefined : json['price'],
    };
}

export function ConsultationTypeRequestToJSON(json: any): ConsultationTypeRequest {
    return ConsultationTypeRequestToJSONTyped(json, false);
}

export function ConsultationTypeRequestToJSONTyped(value?: ConsultationTypeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'description': value['description'],
        'price': value['price'],
    };
}

