/* tslint:disable */
/* eslint-disable */
/**
 * Task Management Service
 * API for managing tasks for patients, doctors, and administrators.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DoctorCompetency } from './DoctorCompetency';
import {
    DoctorCompetencyFromJSON,
    DoctorCompetencyFromJSONTyped,
    DoctorCompetencyToJSON,
    DoctorCompetencyToJSONTyped,
} from './DoctorCompetency';

/**
 * 
 * @export
 * @interface CreateDoctorCompetencies201Response
 */
export interface CreateDoctorCompetencies201Response {
    /**
     * 
     * @type {string}
     * @memberof CreateDoctorCompetencies201Response
     */
    message?: string;
    /**
     * 
     * @type {Array<DoctorCompetency>}
     * @memberof CreateDoctorCompetencies201Response
     */
    data?: Array<DoctorCompetency>;
}

/**
 * Check if a given object implements the CreateDoctorCompetencies201Response interface.
 */
export function instanceOfCreateDoctorCompetencies201Response(value: object): value is CreateDoctorCompetencies201Response {
    return true;
}

export function CreateDoctorCompetencies201ResponseFromJSON(json: any): CreateDoctorCompetencies201Response {
    return CreateDoctorCompetencies201ResponseFromJSONTyped(json, false);
}

export function CreateDoctorCompetencies201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDoctorCompetencies201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(DoctorCompetencyFromJSON)),
    };
}

export function CreateDoctorCompetencies201ResponseToJSON(json: any): CreateDoctorCompetencies201Response {
    return CreateDoctorCompetencies201ResponseToJSONTyped(json, false);
}

export function CreateDoctorCompetencies201ResponseToJSONTyped(value?: CreateDoctorCompetencies201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(DoctorCompetencyToJSON)),
    };
}

