/* tslint:disable */
/* eslint-disable */
/**
 * Task Management Service
 * API for managing tasks for patients, doctors, and administrators.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTaskRequest
 */
export interface CreateTaskRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateTaskRequest
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskRequest
     */
    status?: CreateTaskRequestStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskRequest
     */
    patientId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskRequest
     */
    doctorId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateTaskRequest
     */
    price?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateTaskRequest
     */
    notes?: string;
}


/**
 * @export
 */
export const CreateTaskRequestStatusEnum = {
    Open: 'Open',
    Closed: 'Closed'
} as const;
export type CreateTaskRequestStatusEnum = typeof CreateTaskRequestStatusEnum[keyof typeof CreateTaskRequestStatusEnum];


/**
 * Check if a given object implements the CreateTaskRequest interface.
 */
export function instanceOfCreateTaskRequest(value: object): value is CreateTaskRequest {
    return true;
}

export function CreateTaskRequestFromJSON(json: any): CreateTaskRequest {
    return CreateTaskRequestFromJSONTyped(json, false);
}

export function CreateTaskRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTaskRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'status': json['status'] == null ? undefined : json['status'],
        'patientId': json['patientId'] == null ? undefined : json['patientId'],
        'doctorId': json['doctorId'] == null ? undefined : json['doctorId'],
        'price': json['price'] == null ? undefined : json['price'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function CreateTaskRequestToJSON(json: any): CreateTaskRequest {
    return CreateTaskRequestToJSONTyped(json, false);
}

export function CreateTaskRequestToJSONTyped(value?: CreateTaskRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'status': value['status'],
        'patientId': value['patientId'],
        'doctorId': value['doctorId'],
        'price': value['price'],
        'notes': value['notes'],
    };
}

