/* tslint:disable */
/* eslint-disable */
/**
 * Task Management Service
 * API for managing tasks for patients, doctors, and administrators.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateDoctorCompetenciesRequestCompetenciesInner
 */
export interface CreateDoctorCompetenciesRequestCompetenciesInner {
    /**
     * 
     * @type {string}
     * @memberof CreateDoctorCompetenciesRequestCompetenciesInner
     */
    doctorId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateDoctorCompetenciesRequestCompetenciesInner
     */
    consultationTypeId: string;
}

/**
 * Check if a given object implements the CreateDoctorCompetenciesRequestCompetenciesInner interface.
 */
export function instanceOfCreateDoctorCompetenciesRequestCompetenciesInner(value: object): value is CreateDoctorCompetenciesRequestCompetenciesInner {
    if (!('doctorId' in value) || value['doctorId'] === undefined) return false;
    if (!('consultationTypeId' in value) || value['consultationTypeId'] === undefined) return false;
    return true;
}

export function CreateDoctorCompetenciesRequestCompetenciesInnerFromJSON(json: any): CreateDoctorCompetenciesRequestCompetenciesInner {
    return CreateDoctorCompetenciesRequestCompetenciesInnerFromJSONTyped(json, false);
}

export function CreateDoctorCompetenciesRequestCompetenciesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDoctorCompetenciesRequestCompetenciesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'doctorId': json['doctorId'],
        'consultationTypeId': json['consultationTypeId'],
    };
}

export function CreateDoctorCompetenciesRequestCompetenciesInnerToJSON(json: any): CreateDoctorCompetenciesRequestCompetenciesInner {
    return CreateDoctorCompetenciesRequestCompetenciesInnerToJSONTyped(json, false);
}

export function CreateDoctorCompetenciesRequestCompetenciesInnerToJSONTyped(value?: CreateDoctorCompetenciesRequestCompetenciesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'doctorId': value['doctorId'],
        'consultationTypeId': value['consultationTypeId'],
    };
}

