/* tslint:disable */
/* eslint-disable */
/**
 * Task Management Service
 * API for managing tasks for patients, doctors, and administrators.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DoctorCompetency
 */
export interface DoctorCompetency {
    /**
     * 
     * @type {string}
     * @memberof DoctorCompetency
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof DoctorCompetency
     */
    doctorId?: string;
    /**
     * 
     * @type {string}
     * @memberof DoctorCompetency
     */
    consultationTypeId?: string;
}

/**
 * Check if a given object implements the DoctorCompetency interface.
 */
export function instanceOfDoctorCompetency(value: object): value is DoctorCompetency {
    return true;
}

export function DoctorCompetencyFromJSON(json: any): DoctorCompetency {
    return DoctorCompetencyFromJSONTyped(json, false);
}

export function DoctorCompetencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): DoctorCompetency {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'doctorId': json['doctorId'] == null ? undefined : json['doctorId'],
        'consultationTypeId': json['consultationTypeId'] == null ? undefined : json['consultationTypeId'],
    };
}

export function DoctorCompetencyToJSON(json: any): DoctorCompetency {
    return DoctorCompetencyToJSONTyped(json, false);
}

export function DoctorCompetencyToJSONTyped(value?: DoctorCompetency | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'doctorId': value['doctorId'],
        'consultationTypeId': value['consultationTypeId'],
    };
}

