/* tslint:disable */
/* eslint-disable */
/**
 * Task Management Service
 * API for managing tasks for patients, doctors, and administrators.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DoctorCompetenciesInnerConsultationType
 */
export interface DoctorCompetenciesInnerConsultationType {
    /**
     * 
     * @type {string}
     * @memberof DoctorCompetenciesInnerConsultationType
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof DoctorCompetenciesInnerConsultationType
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof DoctorCompetenciesInnerConsultationType
     */
    price?: number;
}

/**
 * Check if a given object implements the DoctorCompetenciesInnerConsultationType interface.
 */
export function instanceOfDoctorCompetenciesInnerConsultationType(value: object): value is DoctorCompetenciesInnerConsultationType {
    return true;
}

export function DoctorCompetenciesInnerConsultationTypeFromJSON(json: any): DoctorCompetenciesInnerConsultationType {
    return DoctorCompetenciesInnerConsultationTypeFromJSONTyped(json, false);
}

export function DoctorCompetenciesInnerConsultationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DoctorCompetenciesInnerConsultationType {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'description': json['description'] == null ? undefined : json['description'],
        'price': json['price'] == null ? undefined : json['price'],
    };
}

export function DoctorCompetenciesInnerConsultationTypeToJSON(json: any): DoctorCompetenciesInnerConsultationType {
    return DoctorCompetenciesInnerConsultationTypeToJSONTyped(json, false);
}

export function DoctorCompetenciesInnerConsultationTypeToJSONTyped(value?: DoctorCompetenciesInnerConsultationType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'description': value['description'],
        'price': value['price'],
    };
}

