/* tslint:disable */
/* eslint-disable */
/**
 * Task Management Service
 * API for managing tasks for patients, doctors, and administrators.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginResponse
 */
export interface LoginResponse {
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    idToken?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    refreshToken?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponse
     */
    tokenType?: string;
    /**
     * 
     * @type {number}
     * @memberof LoginResponse
     */
    expiresIn?: number;
}

/**
 * Check if a given object implements the LoginResponse interface.
 */
export function instanceOfLoginResponse(value: object): value is LoginResponse {
    return true;
}

export function LoginResponseFromJSON(json: any): LoginResponse {
    return LoginResponseFromJSONTyped(json, false);
}

export function LoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'idToken': json['idToken'] == null ? undefined : json['idToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
        'tokenType': json['tokenType'] == null ? undefined : json['tokenType'],
        'expiresIn': json['expiresIn'] == null ? undefined : json['expiresIn'],
    };
}

export function LoginResponseToJSON(json: any): LoginResponse {
    return LoginResponseToJSONTyped(json, false);
}

export function LoginResponseToJSONTyped(value?: LoginResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accessToken': value['accessToken'],
        'idToken': value['idToken'],
        'refreshToken': value['refreshToken'],
        'tokenType': value['tokenType'],
        'expiresIn': value['expiresIn'],
    };
}

