/* tslint:disable */
/* eslint-disable */
/**
 * Task Management Service
 * API for managing tasks for patients, doctors, and administrators.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostImageRequest
 */
export interface PostImageRequest {
    /**
     * 
     * @type {string}
     * @memberof PostImageRequest
     */
    patientId?: string;
    /**
     * Base64 encoded string of the image
     * @type {string}
     * @memberof PostImageRequest
     */
    base64Data?: string;
    /**
     * 
     * @type {string}
     * @memberof PostImageRequest
     */
    type?: string;
}

/**
 * Check if a given object implements the PostImageRequest interface.
 */
export function instanceOfPostImageRequest(value: object): value is PostImageRequest {
    return true;
}

export function PostImageRequestFromJSON(json: any): PostImageRequest {
    return PostImageRequestFromJSONTyped(json, false);
}

export function PostImageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostImageRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'patientId': json['patientId'] == null ? undefined : json['patientId'],
        'base64Data': json['base64Data'] == null ? undefined : json['base64Data'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function PostImageRequestToJSON(json: any): PostImageRequest {
    return PostImageRequestToJSONTyped(json, false);
}

export function PostImageRequestToJSONTyped(value?: PostImageRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'patientId': value['patientId'],
        'base64Data': value['base64Data'],
        'type': value['type'],
    };
}

