/* tslint:disable */
/* eslint-disable */
/**
 * Task Management Service
 * API for managing tasks for patients, doctors, and administrators.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PutConsultationTypeByIdRequest
 */
export interface PutConsultationTypeByIdRequest {
    /**
     * 
     * @type {string}
     * @memberof PutConsultationTypeByIdRequest
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof PutConsultationTypeByIdRequest
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof PutConsultationTypeByIdRequest
     */
    price?: number;
}

/**
 * Check if a given object implements the PutConsultationTypeByIdRequest interface.
 */
export function instanceOfPutConsultationTypeByIdRequest(value: object): value is PutConsultationTypeByIdRequest {
    return true;
}

export function PutConsultationTypeByIdRequestFromJSON(json: any): PutConsultationTypeByIdRequest {
    return PutConsultationTypeByIdRequestFromJSONTyped(json, false);
}

export function PutConsultationTypeByIdRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PutConsultationTypeByIdRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'description': json['description'] == null ? undefined : json['description'],
        'price': json['price'] == null ? undefined : json['price'],
    };
}

export function PutConsultationTypeByIdRequestToJSON(json: any): PutConsultationTypeByIdRequest {
    return PutConsultationTypeByIdRequestToJSONTyped(json, false);
}

export function PutConsultationTypeByIdRequestToJSONTyped(value?: PutConsultationTypeByIdRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'description': value['description'],
        'price': value['price'],
    };
}

