/* tslint:disable */
/* eslint-disable */
/**
 * Task Management Service
 * API for managing tasks for patients, doctors, and administrators.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTaskRequest
 */
export interface UpdateTaskRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskRequest
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskRequest
     */
    doctorId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateTaskRequest
     */
    price?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateTaskRequest
     */
    notes?: string;
}

/**
 * Check if a given object implements the UpdateTaskRequest interface.
 */
export function instanceOfUpdateTaskRequest(value: object): value is UpdateTaskRequest {
    return true;
}

export function UpdateTaskRequestFromJSON(json: any): UpdateTaskRequest {
    return UpdateTaskRequestFromJSONTyped(json, false);
}

export function UpdateTaskRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTaskRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'doctorId': json['doctorId'] == null ? undefined : json['doctorId'],
        'price': json['price'] == null ? undefined : json['price'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function UpdateTaskRequestToJSON(json: any): UpdateTaskRequest {
    return UpdateTaskRequestToJSONTyped(json, false);
}

export function UpdateTaskRequestToJSONTyped(value?: UpdateTaskRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'doctorId': value['doctorId'],
        'price': value['price'],
        'notes': value['notes'],
    };
}

