openapi: 3.0.1
info:
  title: Task Management Service
  description: API for managing tasks for patients, doctors, and administrators.
  version: 1.0.0

servers:
  - url: /prod

paths:
  /auth/login:
    post:
      operationId: postAuthLogin
      summary: Authenticate a user
      description: No roles are required to authenticate
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: User authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'

  /patient/images:
    post:
      operationId: postPatientImages
      summary: Upload diagnostic images
      description: Roles Allowed **Patient**
      security:
        - bearerAuth: [ ] # Secure this endpoint with Cognito
      x-roles:
        - Admin
      tags:
        - Patient
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImageUploadRequest'
      responses:
        '201':
          description: Image uploaded

  /patient/tasks:
    get:
      operationId: getPatientTasks
      summary: Retrieve all tasks for the patient
      description: Roles Allowed **Patient**
      tags:
        - Patient
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

  /patient/tasks/{taskId}:
    get:
      operationId: getPatientTaskById
      summary: Retrieve details of a specific task
      description: Roles Allowed **Patient**
      tags:
        - Patient
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

  /doctor/tasks:
    get:
      operationId: getDoctorTasks
      summary: Retrieve all tasks assigned to the doctor
      description: Roles Allowed **Doctor**
      tags:
        - Doctor
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

  /doctor/tasks/{taskId}:
    get:
      operationId: getDoctorTaskById
      summary: Retrieve details of a specific task
      description: Roles Allowed **Doctor**
      tags:
        - Doctor
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

    put:
      operationId: updateDoctorTask
      description: Roles Allowed **Doctor**
      tags:
        - Doctor
      summary: Update task status and add notes
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdateRequest'
      responses:
        '200':
          description: Task updated

  /admin/users:
    post:
      operationId: postAdminUsers
      summary: Create a new user (patient or doctor)
      description: Roles Allowed **Admin**
      tags:
        - Admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /admin/users/{userId}:
    put:
      operationId: putAdminUserById
      tags:
        - Admin
      summary: Update details of an existing user
      description: Roles Allowed **Admin**
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
      responses:
        '200':
          description: User updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

    delete:
      operationId: deleteAdminUserById
      summary: Remove a user
      description: Roles Allowed **Admin**
      tags:
        - Admin
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: User removed

  /admin/consultation-types:
    post:
      tags:
        - Admin
      operationId: postAdminConsultationTypes
      summary: Add a new consultation type
      description: Roles Allowed **Admin**
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConsultationTypeRequest'
      responses:
        '201':
          description: Consultation type added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsultationType'
  /consultation-types:
    get:
      operationId: getAdminConsultationTypes
      tags:
        - Admin
      summary: Retrieve all consultation types
      responses:
        '200':
          description: List of consultation types
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ConsultationType'

  /admin/consultation-types/{id}:
    put:
      operationId: putAdminConsultationTypeById
      tags:
        - Admin
      summary: Update a consultation type
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  example: "Updated Consultation"
                description:
                  type: string
                  example: "Updated description"
                price:
                  type: number
                  example: 120.0
      responses:
        '200':
          description: Consultation type updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConsultationType'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string

    LoginResponse:
      type: object
      properties:
        token:
          type: string

    ImageUploadRequest:
      type: object
      properties:
        type:
          type: string
        url:
          type: string

    Task:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        status:
          type: string
        patientId:
          type: string
        doctorId:
          type: string
        createdAt:
          type: string
          description: "ISO 8601 format for date-time (e.g., 2023-12-01T00:00:00Z)"
        price:
          type: number
        notes:
          type: string

    TaskUpdateRequest:
      type: object
      properties:
        status:
          type: string
        notes:
          type: string

    CreateUserRequest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        phone:
          type: string
        role:
          type: string
          enum: [patient, doctor]

    UpdateUserRequest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        phone:
          type: string

    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        phone:
          type: string

    ConsultationTypeRequest:
      type: object
      properties:
        type:
          type: string
        description:
          type: string
        price:
          type: number

    ConsultationType:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        description:
          type: string
        price:
          type: number
